version: '3'

services:
  nats:
    image: nats
    expose:
      - 4222

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - auth

  auth:
    build:
      context: .
    command: yarn dev auth
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - nats
    ports:
      - 8080

  stage:
    build:
      context: .
    command: yarn dev stage
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - nats
      - auth
    ports:
      - 8080

volumes:
  node_modules:
