version: '3'

services:
  base_node:
    image: base_node
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: base_node

  mongodb0:
    image: mongo:4.0-xenial
    container_name: mongodb_0
    hostname: mongodb0
    volumes:
      - mongodb_data0:/data/db
    restart: always
    command: --bind_ip_all --replSet "rs0" --oplogSize 128

  mongodb1:
    image: mongo:4.0-xenial
    container_name: mongodb_1
    hostname: mongodb1
    volumes:
      - mongodb_data1:/data/db
    restart: always
    command: --bind_ip_all --replSet "rs0" --oplogSize 128

  mongodb2:
    image: mongo:4.0-xenial
    container_name: mongodb_2
    hostname: mongodb2
    volumes:
      - mongodb_data2:/data/db
    restart: always
    command: --bind_ip_all --replSet "rs0" --oplogSize 128

  mongo_setup:
    container_name: mongo_setup
    image: mongo:4.0-xenial
    restart: on-failure
    volumes:
      - ./mongo:/mongo
    command: 'mongo/setup.sh'
    depends_on:
      - mongodb0
      - mongodb1
      - mongodb2

  adminmongo:
    image: 'mrvautin/adminmongo'
    container_name: adminmongo
    environment:
      # work around but this might break in the future https://github.com/mrvautin/adminMongo/issues/229
      - HOST=0.0.0.0
    ports:
      - 1234:1234

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379

  nats:
    image: nats
    container_name: nats
    expose:
      - 4222

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - auth

  # Gateway
  stage:
    container_name: stage_gateway
    image: base_node:latest
    command: nodemon --watch src/core --watch src/services/stage src/index.js stage
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - base_node
      - nats
      - mongo_setup
      - redis
    ports:
      - 8080

  # Services
  auth:
    container_name: auth_service
    image: base_node:latest
    command: nodemon --watch src/core --watch src/services/auth src/index.js auth
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - base_node
      - nats

  user:
    container_name: user_service
    image: base_node:latest
    command: nodemon --watch src/core --watch src/services/user src/index.js user
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - base_node
      - nats

volumes:
  node_modules:
  mongodb_data0:
  mongodb_data1:
  mongodb_data2:
